<?php 
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$pickupData = $this->getQuote()->getPickupData();
	$_rate = $this->getRate();
//	if(!isset($pickupData['store']))
//	{
//		$pickupData['store'] = -1;
//	}
//	if(!isset($pickupData['name']))
//	{
//		$pickupData['name'] = '';
//	}
?>
<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">

    <li>
        <label for="<?php echo $_code ?>_store" class="required"><em>*</em><?php echo $this->__('Choose Store Location:') ?></label>
        <span class="input-box">

            <select class="required-entry" name="shipping_pickup[store]">
                <option value='' <?php if($pickupData['store'] == ''){ echo "selected=selected";} ?>><?php echo $this->__('Select Store..');?></option>
                <?php
                $config = Mage::helper('pickup')->getConfigFieldOne();
                foreach ($config as $row) { ?>
                    <option value='<?php echo $row['pickup_name'] ?>' <?php if($pickupData['store'] == $row['pickup_name']){ echo "selected=selected";} ?>><?php echo $row['pickup_name'] ?></option>
                <?php } ?>

            </select>
        </span>
<!--        <label for="--><?php //echo $_code ?><!--_store" class="required"><em>*</em>--><?php //echo $this->__("Pickup Person's Name:") ?><!--</label>-->
<!--        <span class="input-box">-->
<!--        	<input type='text' name='shipping_pickup[name]' class='required-entry input-text' value='--><?php //echo $pickupData['name']?><!--' />-->
<!--        </span>-->
    </li>
</ul>